plugin: yc_compute
folders:
 - b1gnnak3h8ukjl8e1h3f
filters:
  - status == 'RUNNING'
auth_kind: serviceaccountfile
service_account_file: ./key.json
hostnames:
  - "{{ name.replace('reddit-', '') }}server"
compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address
  internal_ip: network_interfaces[0].primary_v4_address.address

keyed_groups:
  - key: labels.tags
    prefix: ''
    separator: ''

groups:
  app: "'reddit-app' in labels.tags"
  db: "'reddit-db' in labels.tags"
